version: "3.8"
services:
  js:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE
    container_name: js-container
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:5173:5173
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./front/fire-station/build
        target: /app/front/fire-station/build
        bind:
          create_host_path: true
  db:
    image: neo4j:4.4.42-community
    container_name: neo4j-container
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    env_file:
      - .env

volumes:
  neo4jdata:
  neo4jlogs:
