version: "3.8"
services:
  js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: js-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - neo4j
  db:
    image: neo4j:4.4.42-community
    container_name: neo4j-container
    env_file:
      - .env
